---
title: "Weather"
author: "Maxwel Coura Oliveira"
date: "10/7/2021"
output: html_document
---

```{r}
library(tidyverse) # Data wrangling
library(lubridate) # Dates operations
library(daymetr)
library(chirps)
library(patchwork)
library(ggtext)
library(ggthemes)
library(nasapower)
library(ggdist)
library(vegan)
#https://cran.r-project.org/web/packages/ggdist/vignettes/slabinterval.html
```


```{r}
# your data
df_time <- tibble(ID = c('1','2'), 
                  Site = c('Lancaster','Brooklyn'),
                  # Both coordinates in decimal format
                  latitude = c(42.83, 42.52),
                  longitude = c(-90.76, -89.23),
                  Start = c('1989-01-01','1989-01-01'),
                  End = c('2020-12-31','2020-12-31')) %>% 
            mutate_at(5:6, ymd) # as date
```



## Daymet 

```{r function}
source("weather_daymet.R")
```



```{r get_data}
#dpp default = 0 - dpp = days prior start date
df_daymet <- weather_daymet(input = df_time, dpp = 0) 
```


```{r}
df_daymet %>% 
  janitor::clean_names() %>% 
  mutate(month_lab = month(date, label = TRUE)) -> weather
```


```{r}
weather %>% 
  filter(month %in% c(5, 6, 7, 8, 9, 10)) %>% 
  mutate(year = as.character(year),
         highlight = ifelse(year %in% c("2019", "2020"), TRUE, FALSE),
         variable = if_else(highlight == TRUE, year, "NA")) -> weather1
```


```{r}
weather1 %>% 
#  filter(year %in% c(2019, 2020)) %>% 
  group_by(site, year, month, month_lab) %>% 
  summarise(prec = sum(pp), tmax = mean(tmax), tmin = mean(tmin), tmean = mean(tmean)) %>% 
  mutate_if(is.double, ~round(., 1)) 
```


```{r}
weather1 %>% 
  filter(month %in% c(5, 6, 7, 8, 9, 10)) %>% 
  mutate(year = as.character(year),
         highlight = ifelse(year %in% c("2019", "2020"), TRUE, FALSE),
         variable = if_else(highlight == TRUE, year, "NA")) -> weather2
```

```{r}
weather2 %>% 
  filter(variable != "NA") %>% 
  ggplot(aes(x = month_lab, y = tmean, 
             fill = variable,
             group = variable)) +
  geom_jitter(data = weather3 %>% 
                filter(variable == "NA"), show.legend = FALSE, 
              color = "#333333", alpha = 0.1, shape = 16) +
#   geom_jitter(position = position_dodge2(width = 0.4),
#              color = "#333333", alpha = 1, shape = 16) +
  stat_gradientinterval(position = position_dodge2()) +
  scale_fill_manual(values = c("red", "blue", "#333333")) +
  facet_grid(~ site) +
  theme_test() +
#  geom_curve(data = text2, 
#             x = 2, y = 13, 
#             xend = 2.5, yend = 16,
#             arrow = arrow(length = unit(0.07, "inch")), 
#             size = 0.4, curvature = -0.3, color = "gray90") + 
  scale_y_continuous(limits = c(0, 33)) +
  labs(x = NULL, y = "Temperature (C)") +
  theme(legend.position = "none") -> temp
ggsave("weather.png", height = 3, width = 6)
```